package com.projectcarv.praciceSet.project2021.Dharmendra.ExceptionText;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import com.projectcarv.praciceSet.project2021.Amarnath.Assignment.Employee;

public class FileTest {

	public static void main(String[] args) {
		
		/*List strList = null;
		strList.add("a");
		strList.add("b");
		strList.add("c");
		
		System.out.println(strList.get(3));*/
		
		/*System.out.println("Before try and catch");
		FileCreator fileCreator = new FileCreator();
		try {
			fileCreator.createFile();
		} catch (UserDefinedException ue) {
			
			System.out.println("I am getting user defined exception witha message --" +ue.getMsg());			
		}  catch (Exception e) {
			
			System.out.println("I am getting  exception witha message --" +e.getMessage());
		} finally {
			System.out.println("I am inside finally block");
		}
		
		System.out.println("Out side of try and catch block");*/
	
		
	}

}
